FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y python3 python3-pip git libgl1-mesa-glx libglib2.0-0 && rm -rf /var/lib/apt/lists/*
WORKDIR /app/autovideo
COPY autovideo/ .
RUN pip install --user -e . -i https://pypi.tuna.tsinghua.edu.cn/simple --only-binary :all:
RUN pip install --user -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --only-binary :all:
ENV PATH=/root/.local/bin:$PATH
CMD ["tail", "-f", "/dev/null"]